In [3]:
import pandas as pd

In [4]:
df= pd.read_csv('Downloads/archive (3)/ecommerce_customer_behavior_dataset_v2.csv')

In [7]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_000001-1,CUST_00001,29-05-2023,40,Male,Ankara,Books,29.18,1,0.00,29.18,Digital Wallet,Mobile,14,9,True,13,4
1,ORD_000001-2,CUST_00001,12-10-2023,40,Male,Ankara,Home & Garden,644.40,1,138.05,506.35,Credit Card,Desktop,14,8,True,6,2
2,ORD_000001-3,CUST_00001,05-12-2023,40,Male,Ankara,Sports,332.82,5,0.00,1664.10,Credit Card,Mobile,15,10,True,9,4
3,ORD_000002-1,CUST_00002,11-05-2023,33,Male,Istanbul,Food,69.30,5,71.05,275.45,Digital Wallet,Desktop,16,13,True,4,4
4,ORD_000002-2,CUST_00002,16-06-2023,33,Male,Istanbul,Beauty,178.15,3,0.00,534.45,Credit Card,Mobile,14,7,True,6,4

In [42]:
df.tail()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Age_Group
17044,ORD_004999-1,CUST_04999,16-01-2024,44,Male,Antalya,Beauty,68.65,2,0.00,137.30,Digital Wallet,Mobile,14,10,False,6,1,36-45
17045,ORD_005000-1,CUST_05000,22-02-2023,24,Female,Eskisehir,Beauty,156.12,1,0.00,156.12,Credit Card,Mobile,15,8,True,7,5,18-25
17046,ORD_005000-2,CUST_05000,29-06-2023,24,Female,Eskisehir,Home & Garden,1065.24,3,0.00,3195.72,Credit Card,Desktop,17,11,True,5,4,18-25
17047,ORD_005000-3,CUST_05000,29-12-2023,24,Female,Eskisehir,Books,47.73,2,8.80,86.66,Credit Card,Desktop,13,11,True,12,2,18-25
17048,ORD_005000-4,CUST_05000,19-01-2024,24,Female,Eskisehir,Home & Garden,1015.23,4,217.01,3843.91,Credit Card,Mobile,15,7,True,3,4,18-25

In [5]:
df.count()

Order_ID                    17049
Customer_ID                 17049
Date                        17049
Age                         17049
Gender                      17049
City                        17049
Product_Category            17049
Unit_Price                  17049
Quantity                    17049
Discount_Amount             17049
Total_Amount                17049
Payment_Method              17049
Device_Type                 17049
Session_Duration_Minutes    17049
Pages_Viewed                17049
Is_Returning_Customer       17049
Delivery_Time_Days          17049
Customer_Rating             17049
dtype: int64

In [9]:
df.shape

(17049, 18)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17049 entries, 0 to 17048
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  17049 non-null  str
 1   Customer_ID               17049 non-null  str
 2   Date                      17049 non-null  str
 3   Age                       17049 non-null  int64
 4   Gender                    17049 non-null  str
 5   City                      17049 non-null  str
 6   Product_Category          17049 non-null  str
 7   Unit_Price                17049 non-null  float64
 8   Quantity                  17049 non-null  int64
 9   Discount_Amount           17049 non-null  float64
 10  Total_Amount              17049 non-null  float64
 11  Payment_Method            17049 non-null  str
 12  Device_Type               17049 non-null  str
 13  Session_Duration_Minutes  17049 non-null  int64
 14  Pages_Viewed              17049 non-null  int64
 15  Is_Returning_Customer     17049 non-null  bool
 16  Delivery_Time_Days        17049 non-null  int64
 17  Customer_Rating           17049 non-null  int64
dtypes: bool(1), float64(3), int64(6), str(8)
memory usage: 3.3 MB

In [11]:
df.describe()

,Age,Unit_Price,Quantity,Discount_Amount,Total_Amount,Session_Duration_Minutes,Pages_Viewed,Delivery_Time_Days,Customer_Rating
count,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000,17049.000000
mean,34.945745,447.901689,3.011379,69.788135,1277.438711,14.535633,9.003109,6.503607,3.899408
std,11.046855,722.319705,1.417027,240.704662,2358.436375,2.925524,2.259954,3.488787,1.128803
min,18.000000,5.050000,1.000000,0.000000,6.210000,4.000000,1.000000,1.000000,1.000000
25%,26.000000,73.260000,2.000000,0.000000,172.970000,13.000000,7.000000,4.000000,3.000000
50%,35.000000,174.680000,3.000000,0.000000,455.850000,15.000000,9.000000,6.000000,4.000000
75%,42.000000,494.570000,4.000000,32.710000,1267.750000,17.000000,11.000000,8.000000,5.000000
max,75.000000,7900.010000,5.000000,6538.290000,37852.050000,26.000000,18.000000,25.000000,5.000000

In [6]:
# which customers spend the most
df.groupby("Customer_ID")["Total_Amount"].sum().sort_values(ascending=False).head(10)

Customer_ID
CUST_01573    50628.15
CUST_00197    47324.23
CUST_03795    42480.02
CUST_00154    41613.83
CUST_04219    40608.39
CUST_03149    39834.61
CUST_03923    38610.82
CUST_01164    36842.41
CUST_01816    36557.27
CUST_04246    36295.30
Name: Total_Amount, dtype: float64

In [8]:
# which customer place the most orders
df.groupby("Customer_ID")["Order_ID"].count().sort_values(ascending=False).head(10)

Customer_ID
CUST_02860    10
CUST_02004    10
CUST_00016    10
CUST_02572    10
CUST_00489    10
CUST_00593    10
CUST_03833    10
CUST_01692    10
CUST_04255    10
CUST_00092    10
Name: Order_ID, dtype: int64

In [9]:
# Which product category is purchesed the most
df.groupby("Product_Category")["Quantity"].sum().sort_values(ascending=False)

Product_Category
Sports           6856
Books            6727
Beauty           6564
Food             6381
Toys             6303
Electronics      6277
Home & Garden    6155
Fashion          6078
Name: Quantity, dtype: int64

In [10]:
# Which product category generates the higest revenue
df.groupby("Product_Category")["Total_Amount"].sum().sort_values(ascending=False)

Product_Category
Electronics      10481897.65
Home & Garden     4023903.94
Sports            3205086.99
Fashion           1577035.70
Toys              1014237.53
Beauty             694437.02
Food               422054.65
Books              360399.11
Name: Total_Amount, dtype: float64

In [11]:
# What is the average order value
df["Total_Amount"].mean()

np.float64(1277.4387113613702)

In [12]:
# How much revenue comes from new vs returning customers
df.groupby("Is_Returning_Customer")["Total_Amount"].sum()

Is_Returning_Customer
False     2588332.13
True     19190720.46
Name: Total_Amount, dtype: float64

In [13]:
# which city generates the higest revenue
df.groupby("City")["Total_Amount"].sum().sort_values(ascending=False).head(10)

City
Istanbul     5646595.78
Ankara       3052443.10
Izmir        2651743.92
Bursa        2317028.10
Antalya      1661594.15
Gaziantep    1573422.25
Adana        1512320.19
Konya        1363152.80
Kayseri      1091658.53
Eskisehir     909093.77
Name: Total_Amount, dtype: float64

In [15]:
# which city has the most orders
df.groupby("City")["Order_ID"].count().sort_values(ascending=False).head(10)

City
Istanbul     4402
Ankara       2422
Izmir        2072
Bursa        1721
Adana        1326
Antalya      1246
Gaziantep    1183
Konya        1120
Kayseri       851
Eskisehir     706
Name: Order_ID, dtype: int64

In [17]:
# which payment method is used the most
df["Payment_Method"].value_counts()

Payment_Method
Credit Card         6801
Debit Card          4321
Digital Wallet      3276
Bank Transfer       1763
Cash on Delivery     888
Name: count, dtype: int64

In [19]:
# which device generates the highest revenue
df.groupby("Device_Type")["Total_Amount"].sum() .sort_values(ascending=False)

Device_Type
Mobile     12028685.29
Desktop     7661437.07
Tablet      2088930.23
Name: Total_Amount, dtype: float64

In [20]:
# Does discount have a relationship with spending
df[["Discount_Amount","Total_Amount"]].corr()

                 Discount_Amount  Total_Amount
Discount_Amount         1.000000      0.456245
Total_Amount            0.456245      1.000000

In [22]:
#Does session duration affect spending
df[["Session_Duration_Minutes","Total_Amount"]].corr()

                          Session_Duration_Minutes  Total_Amount
Session_Duration_Minutes                  1.000000     -0.008717
Total_Amount                             -0.008717      1.000000

In [23]:
# Does viewing more pages relate to higher spending
df[["Pages_Viewed","Total_Amount"]].corr()

              Pages_Viewed  Total_Amount
Pages_Viewed      1.000000      0.008851
Total_Amount      0.008851      1.000000

In [26]:
# does delivery time affect customers rating
df.groupby("Delivery_Time_Days")["Customer_Rating"].mean()

Delivery_Time_Days
1     3.755365
2     3.912029
3     3.924433
4     3.878626
5     3.914836
6     3.916626
7     3.912218
8     3.917282
9     3.903196
10    3.878750
11    3.832196
12    3.872137
13    3.864238
14    3.920188
15    3.929936
16    3.819444
17    3.739726
18    3.928571
19    3.857143
20    3.885714
21    4.000000
22    3.923077
23    3.727273
24    4.100000
25    3.125000
Name: Customer_Rating, dtype: float64

In [41]:
# which age group spend most
bins=[0,18,25,35,45,55,100]

lable=["<18","18-25","26-35","36-45","46-55","56+"]

df["Age_Group"]=pd.cut(df["Age"],bins=bins,
labels=lable)

df.groupby("Age_Group",observed=True)["Total_Amount"].sum().sort_values(ascending=False)

Age_Group
26-35    6623009.07
36-45    6431670.03
46-55    3010626.51
18-25    2884081.58
<18      2084936.48
56+       744728.92
Name: Total_Amount, dtype: float64

In [29]:
# which gender has higher average spending
df.groupby("Gender")["Total_Amount"].mean().sort_values(ascending=False)

Gender
Other     1530.316500
Female    1281.549356
Male      1265.066744
Name: Total_Amount, dtype: float64

In [31]:
# what is the average quantity purchased per order 
df["Quantity"].mean()

np.float64(3.0113789665082997)

In [34]:
# what percentage of customer are returning customers
df["Customer_Rating"].mean()

np.float64(3.89940758988797)

In [33]:
# waht is the  overall distribution of customer spending
df["Total_Amount"].describe()

count    17049.000000
mean      1277.438711
std       2358.436375
min          6.210000
25%        172.970000
50%        455.850000
75%       1267.750000
max      37852.050000
Name: Total_Amount, dtype: float64